### ISSUE TITLE
[Feat] Signup page mock api connection

### ISSUE THREAD

**Issue by k-wisdom** [Linkup-3mw/frontend#18]
## Description
회원 가입 페이지 mock api 연동 및 유효성 검사 수정

## Todo
- [x] json-server 라이브러리를 활용해 api연동
- [x] 이메일 인증, 기업 인증, 닉네임 인증에 대한 validation 추가
- [x] 기타 버그 수정
