### ISSUE TITLE
[Design] Search page mobile publishing

### ISSUE THREAD

**Issue by luvmac** [Linkup-3mw/frontend#33]
## Todo
- [x] 탐색 페이지 모바일 화면 구현하기
- [x] 탐색 페이지 빌딩 상세화면에 이미지 추가하기 
- [x] 탐색 페이지 필터 디자인하기
