### ISSUE TITLE
[Feat] Signup API Connection

### ISSUE THREAD

**Issue by k-wisdom** [Linkup-3mw/frontend#40]
## Description
회원가입 api 연결

## Todo
- [x] 회원가입 api연결
- [x] 이메일 인증 처리
- [x] 기업 코드 인증 처리
- [x] 닉네임 인증 처리

## ETC
- lodash.debounce 라이브러리 추가
- 환경변수 추가
NEXT_PUBLIC_API_URL="http://ec2-15-164-220-62.ap-northeast-2.compute.amazonaws.com:8080/api/v1"
