### ISSUE TITLE
[Design] Club mobile publishing

### ISSUE THREAD

**Issue by moonyah** [Linkup-3mw/frontend#58]
## Todo
- [x] club page mobile
- [x] club card mobile
- [x] club list 반응형
- [x] my club menu 반응형
- [x] 장소 dropdown 수정
- [x] 전체 소모임 부분 수정, 소모임 카드 수정
- [x] 카테고리 모달 모바일
- [x] 내 소모임 - 가입 모임 - 관리자 뱃지 모바일 수정
- [x] 소모임 개설 모바일
- [x] 완료 모달 모바일
- [x] 모임 관리 페이지 모바일
- [x] 소모임 가입 신청
- [x] 소모임 가입 신청 - 모바일
- [x] 커뮤니티 메뉴바 고정
- [x] 신청 취소, 관리 하기 버튼 수정 - 모바일
---
- [x] HamburgerModel에서 링크 클릭하면 모달 닫히게
