### ISSUE TITLE
[Feat] Add and Fix Club

### ISSUE THREAD

**Issue by moonyah** [Linkup-3mw/frontend#59]
## Description

- 기능 추가 및 API 연결 준비

## Todo
- [ ] 장소 선택 분류
- [ ] 카테고리 분류
- [ ] 팀원 제외 분류
- [ ] 찜 기능
- [ ] 검색 기능
- [ ] 소모임 개설 폼 - 검색
- [ ] 소모임 개설 폼 -> 승인 유형 유효성
- [ ] 소모임 개설 폼 상세 소개 input 수정
- [ ] 소모임 가입 신청
- [ ] 내 소모임 - 가입한 모든 모임 목록
- [ ] 내 소모임 - 가입한 모든 모임 - 관리자, 호스트 구분
- [ ] 내 소모임 - 승인 대기 중인 모임 목록
- [ ] 내 소모임 - 승인 대기 중인 모임 - 신청 취소
- [ ] 내 소모임 - 모임 관리하기 목록
- [ ] 내 소모임 - 모임 관리하기 목록 - 관리하기
- [ ] 내 소모임 - 모임 관리하기 목록 - 관리하기 - 멤버 리스트 기능
- [ ] 신청서 관리 기능 (승인, 거절)
---
- [ ] 인기 소모임 가로로 2줄 있게
- [ ] 검색창 내 "X" 아이콘
