### ISSUE TITLE
[Chore] Community file structure changes and add CommunityNav

### ISSUE THREAD

**Issue by moonyah** [Linkup-3mw/frontend#8]
## Description

Community file structure changes and add CommunityNav

## Todo
- [x] Community file structure changes

> 📦community
┣ 📂(pages)
┃ ┣ 📂club
┃ ┃ ┗ 📜page.tsx
┃ ┣ 📂coffechat
┃ ┃ ┗ 📜page.tsx
┃ ┣ 📂collaboration
┃ ┃ ┗ 📜page.tsx
┃ ┗ 📂event
┃ ┃ ┗ 📜page.tsx
┣ 📂components
┃ ┣ 📂club
┃ ┣ 📂coffechat
┃ ┣ 📂collaboration
┃ ┗ 📂event
┗ 📜page.tsx
- [x] Add CommunityNav
- [x] add CommunityNav icon hover
- [x] add favicon.ico
