### ISSUE TITLE
[Fix] Fix Club and Header

### ISSUE THREAD

**Issue by moonyah** [Linkup-3mw/frontend#88]
## Todo
- [x]  기능 안되는 거 빼기
- [x]  햄버거 모달 열릴 때, 뒤에 스크롤 되게 하기
- [x]  프로필 이상하게 나오는 거 수정 - 가로로 나란히 안 나오는 거 해결
- [x]  header 영역 ssr로 변경 ⇒ 새로고침 때마다, “로그인 하기” ⇒ “OOO님”으로 바뀌는 문제 해결
- [x] Club.tsx 분리 및 컴포넌트 정리
- [x] 폼모달 페이지 분리
